### PR TITLE
Nolibyaml

### PR DESCRIPTION
**Pull request by rainwoodman**
This supersedes PR #18

### CODE REVIEW

**Comment by rainwoodman** [comment]
travis is red. Did you forget to commit the data dir?

**Comment by arteymix** [comment]
Just forgot the Makefile, but here it is!

**Comment by rainwoodman** [comment]
Good. Travis is green. I'll take care of the manual merge.

**Comment by arteymix** [comment]
Maybe you should drop the rename for the pkg-config file, I think it's better to do it at once with Meson integration.

**Comment by rainwoodman** [comment]
You mean stuff in the data directory?

**Comment by rainwoodman** [comment]
It's fine... The meson PR we shall wait a bit. 0.36 is not in Fedora main repo.

**Pull request merged**
