### PR TITLE
Rename 'libyaml-1.0.vapi' for 'yaml-0.1.vapi'

### PR DESCRIPTION
**Pull request by arteymix**
It is the rule to name VAPI the same as the pkg-config file. This is used by Vala to implicitly resolve C flags.

Basically, it allow one to compile directly with `valac --pkg=yaml-0.1 some-source.vala`.

### CODE REVIEW

**Comment by rainwoodman** [comment]
Did you notice there are libyaml-1.0.pc.in file in libyaml directory?

I thought the package name is libyaml, not yaml.

**Comment by rainwoodman** [comment]
I see. It is because of this:

https://github.com/yaml/libyaml/commit/242a44b6a64b9781b0288b0d9ce1e7b6b83c0907

Do you want to in this PR directly update the embeded libyaml to a newer version?

**Comment by rainwoodman** [comment]
Yay! Travis is green. You can rebase and see it.

**Comment by arteymix** [comment]
I'll rebase this on an up-to-date LibYAML then. It will make much more sense.

**Comment by arteymix** [comment]
Would you prefer a submodule instead? It's kind of silly to commit all these changes.

**Comment by rainwoodman** [comment]
Sub module is cool. But what about getting rid of the embeded libyaml in the long run?

**Comment by rainwoodman** [comment]
Travis complains:

```
/usr/bin/valac  --vapidir ../src -C libyaml-glib-parser.vala --pkg libyaml-glib-1.0

error: Package `libyaml-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories

Compilation failed: 1 error(s), 0 warning(s)

make[2]: *** [libyaml-glib-parser.c] Error 1
```

**Comment by arteymix** [comment]
It would be great, it's already pre-installed everywhere.

It must be the transition libyaml-1.0 -> yaml-0.1, I'll check that in a few.

**Comment by arteymix** [comment]
It's the deps file that refer to the old name. If we make the dependency private, that won't be a problem. I'll fixup the first commit.

**Comment by arteymix** [comment]
It must have never really worked against the pre-installed: the pkg-config name is wrong and the version unsatisfiable. I'll fix that and remove it completely from the tree.

**Comment by rainwoodman** [comment]
Things did improve in the last 7 years!

Your latest commit is no longer linking against libyaml in the tests directory.  

I'd say we drop the internal libyaml in this PR.
It would make local testing easier for things like this.

**Comment by arteymix** [comment]
Could you fix the missing linkage? I really fail at autotools (thus I use Meson).

**Comment by rainwoodman** [comment]
Sorry having a bad week. I will do it later of the week.

**Comment by arteymix** [comment]
Yeah, me too, quite busy now. I'll try to follow up this week-end.

**Comment by rainwoodman** [comment]
Hi, I fixed this in PR #21. It was simply because LIBYAML_LIBS were missing in Makefile.am.

I sent you a collaborator invitation so that you can directly push to that branch instead.

**Pull request closed without merging**
